server:
  port: 8080
spring:
  datasource:
    url: jdbc:hsqldb:mem:mydb
    test-on-borrow: true
    test-while-idle: true
    validation-query: select 1;
    maxActive: 1
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
        ddl-auto: create
        hbm2ddl:
          import_files: